name: ${project.name}
version: ${project.version}
main: ${project.groupId}.${project.artifactId}.${project.name}
description: |
    ${project.description}
authors: [puppy3276]
commands:
  duty:
    description: Go on duty!
    permission: guards.duty
  dutyreset:
    description: Reset duty inv
    permission: guards.duty
  guards:
    description: View active guards